apiVersion: v1
appVersion: "2.0.4"
description: Eclipse Mosquitto - An open source MQTT broker 
name: mosquitto
version: 0.3.4
keywords:
  - message queue
  - MQTT
  - mosquitto
  - eclipse-iot
home: https://mosquitto.org/
icon: https://mosquitto.org/images/mosquitto-text-side-28.png
sources:
  - https://github.com/eclipse/mosquitto
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
  - name: Chris Carlson
    email: chris@compucounts.com
