name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      
      - name: Run chart-testing (lint)
        id: lint
        uses: HexF/chart-testing-action@v3.0.0
        with:
          command: lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          install_local_path_provisioner: false
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: HexF/chart-testing-action@v3.0.0
        with:
          command: install
          
      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_repo_url: https://chrispyduck.github.io/charts
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
